"use client";

import { useState, useCallback, useEffect, useRef } from "react";

interface ResultViewerProps {
  summary: string;
  bullets?: string[] | null;
  keywords?: string[] | null;
  isLoading: boolean;
  error?: string;
}

export default function ResultViewer({ summary, bullets, keywords, isLoading, error }: ResultViewerProps) {
  const [copied, setCopied] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  const wordCount = summary.trim() ? summary.trim().split(/\s+/).length : 0;

  const getFullText = useCallback(() => {
    let text = "";
    if (bullets && bullets.length > 0) {
      text = bullets.map((b) => `• ${b}`).join("\n");
    } else {
      text = summary;
    }
    if (keywords && keywords.length > 0) {
      text += `\n\nKeywords: ${keywords.join(", ")}`;
    }
    return text;
  }, [summary, bullets, keywords]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(getFullText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Copy failed
    }
  }, [getFullText]);

  const handleDownloadTxt = useCallback(() => {
    const blob = new Blob([getFullText()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `summary-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [getFullText]);

  const handleSpeak = useCallback(() => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      const text = getFullText();
      if (!text.trim()) return;
      window.speechSynthesis.cancel(); // Prevent stuck speech
      const utterance = new SpeechSynthesisUtterance(text);

      // Auto-detect Hindi script for proper pronunciation
      const isHindi = /[\u0900-\u097F]/.test(text);
      utterance.lang = isHindi ? "hi-IN" : "en-US";

      // Use a cute/female voice if available
      const voices = window.speechSynthesis.getVoices();
      let selectedVoice = null;

      if (isHindi) {
        selectedVoice = voices.find(v => v.lang.includes("hi") && (v.name.includes("Female") || v.name.includes("Google")));
      } else {
        selectedVoice = voices.find(v =>
          (v.lang.includes("en") && (v.name.includes("Female") || v.name.includes("Zira") || v.name.includes("Samantha")))
        );
      }

      if (selectedVoice) {
        utterance.voice = selectedVoice;
      }

      // Adjust pitch for a slightly "cuter" tone
      utterance.pitch = 1.2;
      utterance.rate = 0.95;

      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false); // Graceful fallback
      utteranceRef.current = utterance; // Prevent garbage collection
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  }, [getFullText, isSpeaking]);

  useEffect(() => {
    return () => window.speechSynthesis.cancel();
  }, []);

  const handleDownloadPdf = useCallback(() => {
    // Generate a simple PDF using a data-URI approach (no external lib required)
    const text = getFullText();
    const lines = text.split("\n");

    // Build a basic HTML document for printing as PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AI Summary</title>
        <style>
          body { font-family: Georgia, serif; margin: 40px; color: #1a1a2e; line-height: 1.8; }
          h1 { color: #dc2626; font-size: 24px; margin-bottom: 20px; border-bottom: 2px solid #fecaca; padding-bottom: 10px; }
          .bullet { margin: 8px 0; padding-left: 20px; }
          .keywords { margin-top: 24px; padding: 16px; background: #fef2f2; border-radius: 8px; }
          .keywords strong { color: #dc2626; }
          .meta { margin-top: 30px; font-size: 12px; color: #94849b; border-top: 1px solid #fecaca; padding-top: 12px; }
        </style>
      </head>
      <body>
        <h1>AI Text Summary</h1>
        ${lines.map(l => l.startsWith("•") ? `<p class="bullet">${l}</p>` : `<p>${l}</p>`).join("")}
        <div class="meta">Generated by AI Text Summarizer &mdash; ${new Date().toLocaleDateString()}</div>
      </body>
      </html>
    `;

    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
      }, 300);
    }
  }, [getFullText]);

  return (
    <div className="animate-slide-up">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <svg className="w-5 h-5" style={{ color: "var(--accent)" }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <h2 className="text-lg font-semibold" style={{ color: "var(--text-primary)" }}>
            Summary Result
          </h2>
        </div>
        {summary && (
          <div className="flex items-center gap-1.5 sm:gap-2 flex-wrap justify-end">
            {/* Read Aloud */}
            <button
              onClick={handleSpeak}
              className={`btn-secondary flex items-center gap-1.5 px-2.5 sm:px-4 ${isSpeaking ? 'text-red-500 border-red-200 bg-red-50' : ''}`}
            >
              {isSpeaking ? (
                <svg className="w-3.5 h-3.5 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 10a1 1 0 011-1h4a1 1 0 011 1v4a1 1 0 01-1 1h-4a1 1 0 01-1-1v-4z" />
                </svg>
              ) : (
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.536 8.464a5 5 0 010 7.072m2.828-9.9a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                </svg>
              )}
              <span className="hidden sm:inline">{isSpeaking ? "Stop" : "Read"}</span>
            </button>
            {/* Copy */}
            <button onClick={handleCopy} className="btn-secondary flex items-center gap-1.5 px-2.5 sm:px-4">
              {copied ? (
                <>
                  <svg className="w-3.5 h-3.5" style={{ color: "var(--success)" }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  <span className="hidden sm:inline" style={{ color: "var(--success)" }}>Copied!</span>
                </>
              ) : (
                <>
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  <span className="hidden sm:inline">Copy</span>
                </>
              )}
            </button>
            {/* TXT */}
            <button onClick={handleDownloadTxt} className="btn-secondary flex items-center gap-1.5 hidden sm:flex">
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              TXT
            </button>
            {/* PDF */}
            <button onClick={handleDownloadPdf} className="btn-secondary flex items-center gap-1.5 hidden sm:flex">
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
              PDF
            </button>
          </div>
        )}
      </div>

      {/* Content */}
      <div
        className="glass-card p-5 min-h-[200px] flex flex-col"
        style={{
          borderColor: summary ? "var(--accent-light)" : "var(--border)",
          borderWidth: "1px",
        }}
      >
        {isLoading ? (
          <div className="flex-1 flex flex-col gap-3">
            <div className="shimmer h-4 w-full" />
            <div className="shimmer h-4 w-11/12" />
            <div className="shimmer h-4 w-4/5" />
            <div className="shimmer h-4 w-9/12" />
            <div className="shimmer h-4 w-3/5 mt-2" />
            <div className="shimmer h-4 w-full" />
            <div className="shimmer h-4 w-10/12" />
          </div>
        ) : error ? (
          <div className="flex-1 flex flex-col items-center justify-center text-center gap-3">
            <div className="w-14 h-14 rounded-2xl flex items-center justify-center" style={{ background: "#fef2f2" }}>
              <svg className="w-7 h-7" style={{ color: "#dc2626" }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <p className="font-semibold text-[0.95rem]" style={{ color: "#dc2626" }}>Connection Error</p>
            <p className="text-sm max-w-xs" style={{ color: "var(--text-muted)" }}>{error}</p>
          </div>
        ) : summary ? (
          <div className="flex-1 space-y-4">
            {/* Bullet Points View */}
            {bullets && bullets.length > 0 ? (
              <ul className="space-y-2">
                {bullets.map((bullet, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span
                      className="w-2 h-2 mt-2 rounded-full shrink-0"
                      style={{ background: "var(--accent)" }}
                    />
                    <span className="text-[0.95rem] leading-relaxed" style={{ color: "var(--text-primary)" }}>
                      {bullet}
                    </span>
                  </li>
                ))}
              </ul>
            ) : (
              /* Paragraph View */
              <p className="leading-relaxed text-[0.95rem]" style={{ color: "var(--text-primary)", lineHeight: "1.8" }}>
                {summary}
              </p>
            )}

            {/* Keywords Section */}
            {keywords && keywords.length > 0 && (
              <div className="keywords-section">
                <div className="flex items-center gap-2 mb-2">
                  <svg className="w-4 h-4" style={{ color: "var(--accent)" }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                  </svg>
                  <span className="text-sm font-semibold" style={{ color: "var(--accent)" }}>Keywords</span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {keywords.map((kw, i) => (
                    <span key={i} className="keyword-tag">{kw}</span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="flex-1 flex flex-col items-center justify-center text-center">
            <div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-4" style={{ background: "var(--accent-soft)" }}>
              <svg className="w-8 h-8" style={{ color: "var(--text-muted)" }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
              </svg>
            </div>
            <p className="text-sm font-medium mb-1" style={{ color: "var(--text-secondary)" }}>
              Your summary will appear here
            </p>
            <p className="text-xs" style={{ color: "var(--text-muted)" }}>
              Enter text above and click Summarize
            </p>
          </div>
        )}
      </div>

      {/* Footer */}
      {summary && (
        <div className="flex items-center gap-3 mt-2.5">
          <span className="word-badge">
            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
            </svg>
            {wordCount} words
          </span>
          {bullets && bullets.length > 0 && (
            <span className="word-badge">
              {bullets.length} points
            </span>
          )}
          {keywords && keywords.length > 0 && (
            <span className="word-badge">
              {keywords.length} keywords
            </span>
          )}
        </div>
      )}
    </div>
  );
}
